infinispan:
  clusterName: infinispan
endpoints:
  hotrod:
    auth: true
    enabled: true
    qop: auth
    serverName: infinispan
  memcached:
    enabled: false
  rest:
    auth: true
    enabled: true
jgroups:
  encrypt: false
  transport: tcp
  dnsPing:
    query: infinispan-ping.quotegame.svc.cluster.local
xsite:
  address: a332aeae1308b11ea8eb402f263de3f8-918681333.eu-central-1.elb.amazonaws.com
  name: SITE1
  port: 55200
  backups:
    - address: a415c1960308b11ea8ece122067c1b85-317576765.us-east-1.elb.amazonaws.com
      name: SITE2
      port: 55200
logging:
  console:
    level: info
  file:
    level: warn
  categories:
    org.infinispan.factories: trace
    org.infinispan: info
    org.jgroups: info
